common:
  name: Lipsiadmin
  email_from: info@lipsiasoft.com
  email_cc: info@lipsiasoft.com
  email_object: Admin
  host_addr: admin.lipisasoft.org

production:
  host_addr: admin.lipsiasoft.org

development:
  host_addr: localhost:3000